package com.auca_hr.AUCA_HR_System.enums;

public enum AcademicRank {
//    PROFESSOR, ASSOCIATE_PROFESSOR, ASSISTANT_PROFESSOR,
//    SENIOR_LECTURER, LECTURER, ASSISTANT_LECTURER, TUTOR
    BACHELOR, MASTER, PHD, OTHER
}